jest.mock('../src/components/pos/payment/SaleInvoiceScreen', () => ({ SaleInvoiceScreen: () => null }));
import React from 'react';
import { act, create } from 'react-test-renderer';
import { Text, TextInput } from 'react-native';
let mockAllowed = true;
const mockSignOut = jest.fn();
const mockSubmit = jest.fn();
const mockCart = { items: [{ product: { id: '1', productId: 1, name: 'Arroz', price: 10, stock: 10 }, quantity: 2, unitPriceCents: 1000 }], itemCount: 2, subtotalCents: 2000, discountCents: 0, totalCents: 2000, cartLocked: false, submission: { status: 'idle' }, saleSubmission: { start: mockSubmit, isLocked: () => false } };
jest.mock('../src/context/PosCartContext', () => ({ usePosCart: () => mockCart }));
jest.mock('../src/context/CashRegisterContext', () => ({ useCashRegister: () => ({ invalidate: jest.fn() }) }));
jest.mock('../src/components/pos/PosRegisterGuard', () => ({ PosRegisterGuard: ({ children }: any) => children }));
jest.mock('../src/context/AuthContext', () => ({ useAuth: () => ({ session: { baseUrl: 'https://tenant.example', accessToken: 'token' }, hasPermission: () => mockAllowed, signOut: mockSignOut }) }));
jest.mock('expo-router', () => ({ router: { back: jest.fn(), replace: jest.fn(), push: jest.fn() } }));
jest.mock('@expo/vector-icons', () => ({ Ionicons: () => null }));
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: ({ children }: any) => children }));
jest.mock('../src/components/motion', () => {
  const React = jest.requireActual('react'); const { View, Pressable } = jest.requireActual('react-native');
  return { FadeInView: (props: any) => React.createElement(View, props), PressableScale: (props: any) => React.createElement(Pressable, props) };
});
jest.mock('../src/components/clients/CustomerEditor', () => ({ CustomerEditor: () => null }));
const mockContext = { operational_context: { branch: null, inventory_location: null, cash_drawer: null }, customer: { default: { id: 1, name: 'Cliente Final' } }, payment_methods: [{ id: 1, name: 'Efectivo', type: 'cash', is_cash: true, is_card: false, is_supported: true, is_available: true, supports_change: true, requires_account: false }], accounts: [], currency: { code: 'HNL', symbol: 'L', price_decimals: 2 }, capabilities: { can_create_sale: true, mixed_payments: false }, tax_config: {}, pricing: {} };
jest.mock('../src/services/pos/mobilePosCheckoutService', () => ({ ...jest.requireActual('../src/services/pos/mobilePosCheckoutService'), getCheckoutContext: async () => mockContext, searchClients: async () => ({ items: [], pagination: {} }), preflightSale: jest.fn(() => new Promise(() => {})) }));
import CheckoutScreen from '../app/pos/checkout';
import { CustomerEditor } from '../src/components/clients/CustomerEditor';
import { emptyCustomer } from '../src/services/clients/customerManagementService';
const flush = async () => { for (let i = 0; i < 10; i++) await Promise.resolve(); };
const press = (root: ReturnType<typeof create>, label: string) => root.root.findAll(node => node.props.accessibilityRole === 'button' && typeof node.props.onPress === 'function' && node.findAllByType(Text).some(child => child.props.children === label))[0].props.onPress();
beforeEach(() => { mockAllowed = true; mockSubmit.mockClear(); jest.useFakeTimers(); });
afterEach(() => jest.useRealTimers());
it('returns from quick create with selected client and preserves cart and entered cash without submitting a sale', async () => {
  const before = JSON.stringify(mockCart.items); let root!: ReturnType<typeof create>;
  await act(async () => { root = create(React.createElement(CheckoutScreen)); await flush(); });
  const paymentInput = root.root.findAllByType(TextInput).find(node => node.props.keyboardType === 'decimal-pad');
  expect(paymentInput).toBeDefined();
  act(() => paymentInput!.props.onChangeText('50.00'));
  await act(async () => { press(root, 'Cambiar'); await flush(); });
  act(() => press(root, 'Nuevo cliente'));
  expect(root.root.findByType(CustomerEditor).props.origin).toBe('pos');
  act(() => root.root.findByType(CustomerEditor).props.onSuccess({ ...emptyCustomer(), id: 9, code: '9', name: 'Nuevo POS' }));
  expect(JSON.stringify(root.toJSON())).toContain('Nuevo POS');
  expect(root.root.findAllByType(TextInput).find(node => node.props.keyboardType === 'decimal-pad')!.props.value).toBe('50.00');
  expect(JSON.stringify(mockCart.items)).toBe(before); expect(mockSubmit).not.toHaveBeenCalled();
  act(() => root.unmount());
});
it('hides quick create without the existing create permission', async () => {
  mockAllowed = false; let root!: ReturnType<typeof create>;
  await act(async () => { root = create(React.createElement(CheckoutScreen)); await flush(); });
  await act(async () => { press(root, 'Cambiar'); await flush(); });
  expect(root.root.findAllByType(Text).some(node => node.props.children === 'Nuevo cliente')).toBe(false);
  act(() => root.unmount());
});
